// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod metadata {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ENTRY_DATA: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ENTRY_DATA: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENTRY_DATA: [EntryData; 3] = [
  EntryData::NONE,
  EntryData::BasicInfo,
  EntryData::SemanticInfo,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EntryData(pub u8);
#[allow(non_upper_case_globals)]
impl EntryData {
  pub const NONE: Self = Self(0);
  pub const BasicInfo: Self = Self(1);
  pub const SemanticInfo: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::BasicInfo,
    Self::SemanticInfo,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::BasicInfo => Some("BasicInfo"),
      Self::SemanticInfo => Some("SemanticInfo"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for EntryData {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for EntryData {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for EntryData {
    type Output = EntryData;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for EntryData {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for EntryData {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for EntryData {}
pub struct EntryDataUnionTableOffset {}

pub enum BasicInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BasicInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BasicInfo<'a> {
  type Inner = BasicInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BasicInfo<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BasicInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BasicInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BasicInfo<'bldr>> {
    let mut builder = BasicInfoBuilder::new(_fbb);
    if let Some(x) = args.description { builder.add_description(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(BasicInfo::VT_NAME, None)}
  }
  #[inline]
  pub fn description(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(BasicInfo::VT_DESCRIPTION, None)}
  }
}

impl ::flatbuffers::Verifiable for BasicInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("description", Self::VT_DESCRIPTION, false)?
     .finish();
    Ok(())
  }
}
pub struct BasicInfoArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub description: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for BasicInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    BasicInfoArgs {
      name: None,
      description: None,
    }
  }
}

pub struct BasicInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BasicInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BasicInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_description(&mut self, description: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BasicInfo::VT_DESCRIPTION, description);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BasicInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BasicInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BasicInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BasicInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BasicInfo");
      ds.field("name", &self.name());
      ds.field("description", &self.description());
      ds.finish()
  }
}
pub enum SemanticInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SemanticInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SemanticInfo<'a> {
  type Inner = SemanticInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SemanticInfo<'a> {
  pub const VT_EXTERNAL_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_PROVENANCE: ::flatbuffers::VOffsetT = 6;
  pub const VT_CONFIDENCE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SemanticInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SemanticInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SemanticInfo<'bldr>> {
    let mut builder = SemanticInfoBuilder::new(_fbb);
    builder.add_confidence(args.confidence);
    if let Some(x) = args.provenance { builder.add_provenance(x); }
    if let Some(x) = args.external_id { builder.add_external_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn external_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SemanticInfo::VT_EXTERNAL_ID, None)}
  }
  #[inline]
  pub fn provenance(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SemanticInfo::VT_PROVENANCE, None)}
  }
  #[inline]
  pub fn confidence(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SemanticInfo::VT_CONFIDENCE, Some(0.0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SemanticInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("external_id", Self::VT_EXTERNAL_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("provenance", Self::VT_PROVENANCE, false)?
     .visit_field::<f32>("confidence", Self::VT_CONFIDENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct SemanticInfoArgs<'a> {
    pub external_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub provenance: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub confidence: f32,
}
impl<'a> Default for SemanticInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    SemanticInfoArgs {
      external_id: None,
      provenance: None,
      confidence: 0.0,
    }
  }
}

pub struct SemanticInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SemanticInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_external_id(&mut self, external_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SemanticInfo::VT_EXTERNAL_ID, external_id);
  }
  #[inline]
  pub fn add_provenance(&mut self, provenance: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SemanticInfo::VT_PROVENANCE, provenance);
  }
  #[inline]
  pub fn add_confidence(&mut self, confidence: f32) {
    self.fbb_.push_slot::<f32>(SemanticInfo::VT_CONFIDENCE, confidence, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SemanticInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SemanticInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SemanticInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SemanticInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SemanticInfo");
      ds.field("external_id", &self.external_id());
      ds.field("provenance", &self.provenance());
      ds.field("confidence", &self.confidence());
      ds.finish()
  }
}
pub enum MetadataEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MetadataEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for MetadataEntry<'a> {
  type Inner = MetadataEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MetadataEntry<'a> {
  pub const VT_DATA_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 6;
  pub const VT_ISOTIME_REF: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    MetadataEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MetadataEntryArgs
  ) -> ::flatbuffers::WIPOffset<MetadataEntry<'bldr>> {
    let mut builder = MetadataEntryBuilder::new(_fbb);
    builder.add_isotime_ref(args.isotime_ref);
    if let Some(x) = args.data { builder.add_data(x); }
    builder.add_data_type(args.data_type);
    builder.finish()
  }


  #[inline]
  pub fn data_type(&self) -> EntryData {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EntryData>(MetadataEntry::VT_DATA_TYPE, Some(EntryData::NONE)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(MetadataEntry::VT_DATA, None)}
  }
  #[inline]
  pub fn isotime_ref(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MetadataEntry::VT_ISOTIME_REF, Some(0)).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_basic_info(&self) -> Option<BasicInfo<'a>> {
    if self.data_type() == EntryData::BasicInfo {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { BasicInfo::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_semantic_info(&self) -> Option<SemanticInfo<'a>> {
    if self.data_type() == EntryData::SemanticInfo {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SemanticInfo::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for MetadataEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<EntryData, _>("data_type", Self::VT_DATA_TYPE, "data", Self::VT_DATA, false, |key, v, pos| {
        match key {
          EntryData::BasicInfo => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<BasicInfo>>("EntryData::BasicInfo", pos),
          EntryData::SemanticInfo => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SemanticInfo>>("EntryData::SemanticInfo", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<u64>("isotime_ref", Self::VT_ISOTIME_REF, false)?
     .finish();
    Ok(())
  }
}
pub struct MetadataEntryArgs {
    pub data_type: EntryData,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    pub isotime_ref: u64,
}
impl<'a> Default for MetadataEntryArgs {
  #[inline]
  fn default() -> Self {
    MetadataEntryArgs {
      data_type: EntryData::NONE,
      data: None,
      isotime_ref: 0,
    }
  }
}

pub struct MetadataEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MetadataEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_data_type(&mut self, data_type: EntryData) {
    self.fbb_.push_slot::<EntryData>(MetadataEntry::VT_DATA_TYPE, data_type, EntryData::NONE);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MetadataEntry::VT_DATA, data);
  }
  #[inline]
  pub fn add_isotime_ref(&mut self, isotime_ref: u64) {
    self.fbb_.push_slot::<u64>(MetadataEntry::VT_ISOTIME_REF, isotime_ref, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MetadataEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MetadataEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<MetadataEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for MetadataEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("MetadataEntry");
      ds.field("data_type", &self.data_type());
      match self.data_type() {
        EntryData::BasicInfo => {
          if let Some(x) = self.data_as_basic_info() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EntryData::SemanticInfo => {
          if let Some(x) = self.data_as_semantic_info() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("data", &x)
        },
      };
      ds.field("isotime_ref", &self.isotime_ref());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `MetadataEntry`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_entry_unchecked`.
pub fn root_as_metadata_entry(buf: &[u8]) -> Result<MetadataEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<MetadataEntry>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `MetadataEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_metadata_entry_unchecked`.
pub fn size_prefixed_root_as_metadata_entry(buf: &[u8]) -> Result<MetadataEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<MetadataEntry>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `MetadataEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_entry_unchecked`.
pub fn root_as_metadata_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MetadataEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<MetadataEntry<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `MetadataEntry` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_entry_unchecked`.
pub fn size_prefixed_root_as_metadata_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MetadataEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<MetadataEntry<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a MetadataEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `MetadataEntry`.
pub unsafe fn root_as_metadata_entry_unchecked(buf: &[u8]) -> MetadataEntry<'_> {
  unsafe { ::flatbuffers::root_unchecked::<MetadataEntry>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed MetadataEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `MetadataEntry`.
pub unsafe fn size_prefixed_root_as_metadata_entry_unchecked(buf: &[u8]) -> MetadataEntry<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<MetadataEntry>(buf) }
}
#[inline]
pub fn finish_metadata_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<MetadataEntry<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_metadata_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<MetadataEntry<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Metadata

