#![allow(unused_imports, dead_code)]


// automatically generated by the FlatBuffers compiler, do not modify
// @generated



#[allow(unused_imports, dead_code)]
pub mod cntm_graph {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_VALUE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_VALUE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_VALUE: [Value; 4] = [
  Value::NONE,
  Value::StringValue,
  Value::IntValue,
  Value::FloatValue,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Value(pub u8);
#[allow(non_upper_case_globals)]
impl Value {
  pub const NONE: Self = Self(0);
  pub const StringValue: Self = Self(1);
  pub const IntValue: Self = Self(2);
  pub const FloatValue: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::StringValue,
    Self::IntValue,
    Self::FloatValue,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::StringValue => Some("StringValue"),
      Self::IntValue => Some("IntValue"),
      Self::FloatValue => Some("FloatValue"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Value {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Value {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Value {
    type Output = Value;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Value {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Value {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Value {}
pub struct ValueUnionTableOffset {}

#[allow(clippy::upper_case_acronyms)]
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum ValueT {
  NONE,
  StringValue(std::boxed::Box<StringValueT>),
  IntValue(std::boxed::Box<IntValueT>),
  FloatValue(std::boxed::Box<FloatValueT>),
}
impl Default for ValueT {
  fn default() -> Self {
    Self::NONE
  }
}
impl ValueT {
  pub fn value_type(&self) -> Value {
    match self {
      Self::NONE => Value::NONE,
      Self::StringValue(_) => Value::StringValue,
      Self::IntValue(_) => Value::IntValue,
      Self::FloatValue(_) => Value::FloatValue,
    }
  }
  pub fn pack<'b>(&self, fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>) -> Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>> {
    match self {
      Self::NONE => None,
      Self::StringValue(v) => Some(v.pack(fbb).as_union_value()),
      Self::IntValue(v) => Some(v.pack(fbb).as_union_value()),
      Self::FloatValue(v) => Some(v.pack(fbb).as_union_value()),
    }
  }
  /// If the union variant matches, return the owned StringValueT, setting the union to NONE.
  pub fn take_string_value(&mut self) -> Option<std::boxed::Box<StringValueT>> {
    if let Self::StringValue(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::StringValue(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the StringValueT.
  pub fn as_string_value(&self) -> Option<&StringValueT> {
    if let Self::StringValue(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the StringValueT.
  pub fn as_string_value_mut(&mut self) -> Option<&mut StringValueT> {
    if let Self::StringValue(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned IntValueT, setting the union to NONE.
  pub fn take_int_value(&mut self) -> Option<std::boxed::Box<IntValueT>> {
    if let Self::IntValue(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::IntValue(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the IntValueT.
  pub fn as_int_value(&self) -> Option<&IntValueT> {
    if let Self::IntValue(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the IntValueT.
  pub fn as_int_value_mut(&mut self) -> Option<&mut IntValueT> {
    if let Self::IntValue(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned FloatValueT, setting the union to NONE.
  pub fn take_float_value(&mut self) -> Option<std::boxed::Box<FloatValueT>> {
    if let Self::FloatValue(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::FloatValue(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the FloatValueT.
  pub fn as_float_value(&self) -> Option<&FloatValueT> {
    if let Self::FloatValue(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the FloatValueT.
  pub fn as_float_value_mut(&mut self) -> Option<&mut FloatValueT> {
    if let Self::FloatValue(v) = self { Some(v.as_mut()) } else { None }
  }
}
pub enum StringValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StringValue<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for StringValue<'a> {
  type Inner = StringValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> StringValue<'a> {
  pub const VT_VAL: ::flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "cntm_graph.StringValue"
  }

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    StringValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args StringValueArgs<'args>
  ) -> ::flatbuffers::WIPOffset<StringValue<'bldr>> {
    let mut builder = StringValueBuilder::new(_fbb);
    if let Some(x) = args.val { builder.add_val(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> StringValueT {
    let val = self.val().map(|x| {
      std::string::ToString::to_string(x)
    });
    StringValueT {
      val,
    }
  }

  #[inline]
  pub fn val(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(StringValue::VT_VAL, None)}
  }
}

impl ::flatbuffers::Verifiable for StringValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("val", Self::VT_VAL, false)?
     .finish();
    Ok(())
  }
}
pub struct StringValueArgs<'a> {
    pub val: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for StringValueArgs<'a> {
  #[inline]
  fn default() -> Self {
    StringValueArgs {
      val: None,
    }
  }
}

pub struct StringValueBuilder<'a: 'b, 'b> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> StringValueBuilder<'a, 'b> {
  #[inline]
  pub fn add_val(&mut self, val: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(StringValue::VT_VAL, val);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>) -> StringValueBuilder<'a, 'b> {
    let start = _fbb.start_table();
    StringValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<StringValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for StringValue<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("StringValue");
      ds.field("val", &self.val());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct StringValueT {
  pub val: Option<std::string::String>,
}
impl Default for StringValueT {
  fn default() -> Self {
    Self {
      val: None,
    }
  }
}
impl StringValueT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>
  ) -> ::flatbuffers::WIPOffset<StringValue<'b>> {
    let val = self.val.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    StringValue::create(_fbb, &StringValueArgs{
      val,
    })
  }
}
pub enum IntValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IntValue<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IntValue<'a> {
  type Inner = IntValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> IntValue<'a> {
  pub const VT_VAL: ::flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "cntm_graph.IntValue"
  }

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    IntValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args IntValueArgs
  ) -> ::flatbuffers::WIPOffset<IntValue<'bldr>> {
    let mut builder = IntValueBuilder::new(_fbb);
    builder.add_val(args.val);
    builder.finish()
  }

  pub fn unpack(&self) -> IntValueT {
    let val = self.val();
    IntValueT {
      val,
    }
  }

  #[inline]
  pub fn val(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(IntValue::VT_VAL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for IntValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("val", Self::VT_VAL, false)?
     .finish();
    Ok(())
  }
}
pub struct IntValueArgs {
    pub val: i64,
}
impl<'a> Default for IntValueArgs {
  #[inline]
  fn default() -> Self {
    IntValueArgs {
      val: 0,
    }
  }
}

pub struct IntValueBuilder<'a: 'b, 'b> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> IntValueBuilder<'a, 'b> {
  #[inline]
  pub fn add_val(&mut self, val: i64) {
    self.fbb_.push_slot::<i64>(IntValue::VT_VAL, val, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>) -> IntValueBuilder<'a, 'b> {
    let start = _fbb.start_table();
    IntValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<IntValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for IntValue<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("IntValue");
      ds.field("val", &self.val());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct IntValueT {
  pub val: i64,
}
impl Default for IntValueT {
  fn default() -> Self {
    Self {
      val: 0,
    }
  }
}
impl IntValueT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>
  ) -> ::flatbuffers::WIPOffset<IntValue<'b>> {
    let val = self.val;
    IntValue::create(_fbb, &IntValueArgs{
      val,
    })
  }
}
pub enum FloatValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FloatValue<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FloatValue<'a> {
  type Inner = FloatValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FloatValue<'a> {
  pub const VT_VAL: ::flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "cntm_graph.FloatValue"
  }

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FloatValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FloatValueArgs
  ) -> ::flatbuffers::WIPOffset<FloatValue<'bldr>> {
    let mut builder = FloatValueBuilder::new(_fbb);
    builder.add_val(args.val);
    builder.finish()
  }

  pub fn unpack(&self) -> FloatValueT {
    let val = self.val();
    FloatValueT {
      val,
    }
  }

  #[inline]
  pub fn val(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(FloatValue::VT_VAL, Some(0.0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for FloatValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f32>("val", Self::VT_VAL, false)?
     .finish();
    Ok(())
  }
}
pub struct FloatValueArgs {
    pub val: f32,
}
impl<'a> Default for FloatValueArgs {
  #[inline]
  fn default() -> Self {
    FloatValueArgs {
      val: 0.0,
    }
  }
}

pub struct FloatValueBuilder<'a: 'b, 'b> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FloatValueBuilder<'a, 'b> {
  #[inline]
  pub fn add_val(&mut self, val: f32) {
    self.fbb_.push_slot::<f32>(FloatValue::VT_VAL, val, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>) -> FloatValueBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FloatValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FloatValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FloatValue<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FloatValue");
      ds.field("val", &self.val());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct FloatValueT {
  pub val: f32,
}
impl Default for FloatValueT {
  fn default() -> Self {
    Self {
      val: 0.0,
    }
  }
}
impl FloatValueT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>
  ) -> ::flatbuffers::WIPOffset<FloatValue<'b>> {
    let val = self.val;
    FloatValue::create(_fbb, &FloatValueArgs{
      val,
    })
  }
}
pub enum PropertyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Property<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Property<'a> {
  type Inner = Property<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Property<'a> {
  pub const VT_KEY: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE_TYPE: ::flatbuffers::VOffsetT = 6;
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 8;

  pub const fn get_fully_qualified_name() -> &'static str {
    "cntm_graph.Property"
  }

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Property { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PropertyArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Property<'bldr>> {
    let mut builder = PropertyBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.add_value_type(args.value_type);
    builder.finish()
  }

  pub fn unpack(&self) -> PropertyT {
    let key = self.key().map(|x| {
      std::string::ToString::to_string(x)
    });
    let value = match self.value_type() {
      Value::NONE => ValueT::NONE,
      Value::StringValue => ValueT::StringValue(std::boxed::Box::new(
        self.value_as_string_value()
            .expect("Invalid union table, expected `Value::StringValue`.")
            .unpack()
      )),
      Value::IntValue => ValueT::IntValue(std::boxed::Box::new(
        self.value_as_int_value()
            .expect("Invalid union table, expected `Value::IntValue`.")
            .unpack()
      )),
      Value::FloatValue => ValueT::FloatValue(std::boxed::Box::new(
        self.value_as_float_value()
            .expect("Invalid union table, expected `Value::FloatValue`.")
            .unpack()
      )),
      _ => ValueT::NONE,
    };
    PropertyT {
      key,
      value,
    }
  }

  #[inline]
  pub fn key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Property::VT_KEY, None)}
  }
  #[inline]
  pub fn value_type(&self) -> Value {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Value>(Property::VT_VALUE_TYPE, Some(Value::NONE)).unwrap()}
  }
  #[inline]
  pub fn value(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Property::VT_VALUE, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn value_as_string_value(&self) -> Option<StringValue<'a>> {
    if self.value_type() == Value::StringValue {
      self.value().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { StringValue::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn value_as_int_value(&self) -> Option<IntValue<'a>> {
    if self.value_type() == Value::IntValue {
      self.value().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { IntValue::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn value_as_float_value(&self) -> Option<FloatValue<'a>> {
    if self.value_type() == Value::FloatValue {
      self.value().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { FloatValue::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Property<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_union::<Value, _>("value_type", Self::VT_VALUE_TYPE, "value", Self::VT_VALUE, false, |key, v, pos| {
        match key {
          Value::StringValue => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<StringValue>>("Value::StringValue", pos),
          Value::IntValue => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IntValue>>("Value::IntValue", pos),
          Value::FloatValue => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<FloatValue>>("Value::FloatValue", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct PropertyArgs<'a> {
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub value_type: Value,
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for PropertyArgs<'a> {
  #[inline]
  fn default() -> Self {
    PropertyArgs {
      key: None,
      value_type: Value::NONE,
      value: None,
    }
  }
}

pub struct PropertyBuilder<'a: 'b, 'b> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PropertyBuilder<'a, 'b> {
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Property::VT_KEY, key);
  }
  #[inline]
  pub fn add_value_type(&mut self, value_type: Value) {
    self.fbb_.push_slot::<Value>(Property::VT_VALUE_TYPE, value_type, Value::NONE);
  }
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Property::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>) -> PropertyBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PropertyBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Property<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Property<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Property");
      ds.field("key", &self.key());
      ds.field("value_type", &self.value_type());
      match self.value_type() {
        Value::StringValue => {
          if let Some(x) = self.value_as_string_value() {
            ds.field("value", &x)
          } else {
            ds.field("value", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Value::IntValue => {
          if let Some(x) = self.value_as_int_value() {
            ds.field("value", &x)
          } else {
            ds.field("value", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Value::FloatValue => {
          if let Some(x) = self.value_as_float_value() {
            ds.field("value", &x)
          } else {
            ds.field("value", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("value", &x)
        },
      };
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PropertyT {
  pub key: Option<std::string::String>,
  pub value: ValueT,
}
impl Default for PropertyT {
  fn default() -> Self {
    Self {
      key: None,
      value: ValueT::NONE,
    }
  }
}
impl PropertyT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>
  ) -> ::flatbuffers::WIPOffset<Property<'b>> {
    let key = self.key.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let value_type = self.value.value_type();
    let value = self.value.pack(_fbb);
    Property::create(_fbb, &PropertyArgs{
      key,
      value_type,
      value,
    })
  }
}
pub enum NodeMetadataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NodeMetadata<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for NodeMetadata<'a> {
  type Inner = NodeMetadata<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NodeMetadata<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_PROPERTIES: ::flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "cntm_graph.NodeMetadata"
  }

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    NodeMetadata { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args NodeMetadataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<NodeMetadata<'bldr>> {
    let mut builder = NodeMetadataBuilder::new(_fbb);
    if let Some(x) = args.properties { builder.add_properties(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> NodeMetadataT {
    let name = self.name().map(|x| {
      std::string::ToString::to_string(x)
    });
    let properties = self.properties().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    NodeMetadataT {
      name,
      properties,
    }
  }

  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(NodeMetadata::VT_NAME, None)}
  }
  #[inline]
  pub fn properties(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Property<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Property>>>>(NodeMetadata::VT_PROPERTIES, None)}
  }
}

impl ::flatbuffers::Verifiable for NodeMetadata<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Property>>>>("properties", Self::VT_PROPERTIES, false)?
     .finish();
    Ok(())
  }
}
pub struct NodeMetadataArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub properties: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Property<'a>>>>>,
}
impl<'a> Default for NodeMetadataArgs<'a> {
  #[inline]
  fn default() -> Self {
    NodeMetadataArgs {
      name: None,
      properties: None,
    }
  }
}

pub struct NodeMetadataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> NodeMetadataBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NodeMetadata::VT_NAME, name);
  }
  #[inline]
  pub fn add_properties(&mut self, properties: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Property<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NodeMetadata::VT_PROPERTIES, properties);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>) -> NodeMetadataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    NodeMetadataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<NodeMetadata<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for NodeMetadata<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("NodeMetadata");
      ds.field("name", &self.name());
      ds.field("properties", &self.properties());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct NodeMetadataT {
  pub name: Option<std::string::String>,
  pub properties: Option<std::vec::Vec<PropertyT>>,
}
impl Default for NodeMetadataT {
  fn default() -> Self {
    Self {
      name: None,
      properties: None,
    }
  }
}
impl NodeMetadataT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b>
  ) -> ::flatbuffers::WIPOffset<NodeMetadata<'b>> {
    let name = self.name.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let properties = self.properties.as_ref().map(|x|{
      let w: std::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    NodeMetadata::create(_fbb, &NodeMetadataArgs{
      name,
      properties,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `NodeMetadata`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_node_metadata_unchecked`.
pub fn root_as_node_metadata(buf: &[u8]) -> Result<NodeMetadata<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<NodeMetadata>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `NodeMetadata` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_node_metadata_unchecked`.
pub fn size_prefixed_root_as_node_metadata(buf: &[u8]) -> Result<NodeMetadata<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<NodeMetadata>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `NodeMetadata` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_node_metadata_unchecked`.
pub fn root_as_node_metadata_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NodeMetadata<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<NodeMetadata<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `NodeMetadata` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_node_metadata_unchecked`.
pub fn size_prefixed_root_as_node_metadata_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NodeMetadata<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<NodeMetadata<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a NodeMetadata and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `NodeMetadata`.
pub unsafe fn root_as_node_metadata_unchecked(buf: &[u8]) -> NodeMetadata<'_> {
  unsafe { ::flatbuffers::root_unchecked::<NodeMetadata>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed NodeMetadata and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `NodeMetadata`.
pub unsafe fn size_prefixed_root_as_node_metadata_unchecked(buf: &[u8]) -> NodeMetadata<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<NodeMetadata>(buf) }
}
#[inline]
pub fn finish_node_metadata_buffer<'a, 'b>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>,
    root: ::flatbuffers::WIPOffset<NodeMetadata<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_node_metadata_buffer<'a, 'b>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a>, root: ::flatbuffers::WIPOffset<NodeMetadata<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod cntm_graph

